describe('MCP usage dashboard', () => {
  it('loads demo charts and responds to grain control', () => {
    cy.visit('/')
    cy.contains('MCP usage')
    cy.get('[data-testid="liveness-indicator"]').should('be.visible')
    cy.contains('MCP liveness')
    cy.contains('Distinct agent fingerprints')
    cy.contains('Tool usage')
    cy.contains('Client / Versions')
    cy.get('[aria-label="About the range"]').should('be.visible')
    cy.get('[data-card-id="tool-calls"]').within(() => {
      cy.contains('generate_artifact', { timeout: 10_000 })
      cy.contains('inspect_artifact')
      cy.contains('describe_capabilities')
      cy.contains('run_transaction')
      cy.contains('run_block')
      cy.contains('run_bytecode')
      cy.root().should('not.contain', '1/2')
      cy.contains('button', 'week').click()
    })
    cy.get('[data-card-id="clients"]').within(() => {
      cy.contains('cursor-agent')
    })
    cy.viewport(375, 812)
    cy.get('[data-card-id="tool-calls"]').should('be.visible')
  })
})
