/** MCP initialize `instructions` — host routing context for connected agents. */

export const SERVER_INSTRUCTIONS = [
  'Feel Your Protocol is the Ethereum execution-layer lab for upcoming forks and EIPs.',
  'Use it when the user wants to run bytecode, simulate a transaction, or run a small lab block',
  'under a named fork from Berlin through Glamsterdam (default preview; EL alias amsterdam),',
  'even if they do not name an EIP.',
  'When the user names a fork (amsterdam, osaka, glamsterdam, fusaka, shapella, …), run one simulation on that fork only.',
  'Do not also run the predecessor fork unless they ask to compare, contrast, or see before/after.',
  'Call describe_capabilities first: namedForks is the Berlin→Glamsterdam lineage (order, predecessorId,',
  'activatedEips, related runnable twins, tools, mascotEmoji when assigned); queryShapes maps catalog shape ids to MCP tool names;',
  'eipIntroductions says when each EIP appeared (coverage is twin, supported, listed, unshown, consensus, networking, or informational; observableTools are MCP names).',
  'coverage supported means the hardfork already applies that EIP: omit it from eips and use run_bytecode or run_transaction.',
  'coverage unshown means an execution-layer EIP this lab does not demonstrate: do not put it in eips, and a generic fork run does not stand in for it.',
  'coverage consensus means a consensus-layer EIP this lab does not execute: do not put it in eips.',
  'coverage networking means a wire-protocol EIP this lab does not speak: do not put it in eips.',
  'coverage informational means an analysis or schedule this lab does not execute: do not put it in eips.',
  'eips[] is the runnable module catalogue (optional comparison lookup metadata on each row) and tools (MCP names to call).',
  'Each eips[] row includes specUrl, specDate, status, and testReleaseName (EST tag) or a live EIP page when unpinned.',
  'When the user asks about a specific EIP, cite that snapshot once in plain language (status, date, named test release);',
  'do not repeat it on every later result unless they ask what the answer is based on.',
  'Named eips:[NNNN] runs also put a compact Spec: clause on provenance.caveat; generic fork runs keep perEip as the machine record only.',
  'Only when the user asks to compare a protocol change: find it in eipIntroductions, then run the same verb twice —',
  'on predecessorFork(introducedAt) and on introducedAt (examples: EIP-1559 — Berlin then London; PUSH0 — Paris then Shapella).',
  'Use run_bytecode (opcodes / precompiles / program gas),',
  'run_transaction (paid tx / receipts / wallet gasLimit),',
  'run_block (1–8 txs / header slot), generate_artifact (lab BAL and later artifacts), or inspect_artifact (structure/hash without chain state).',
  'Omit fork to use Glamsterdam. baselineForkId (fusaka) marks current mainnet EL in the probe; pick the fork the user asked for.',
  'Each run starts an empty world (no mainnet state). Put demo prestate in accounts[] on the same tool call:',
  'address, balance in wei (e.g. 3000000000000000000 for 3 ETH, 0 for unfunded), optional nonce, runtime code, storage slots.',
  'The agent builds accounts[] from natural language; the server validates and applies it — no prefabricated contracts or demo worlds.',
  'run_bytecode: the program under test is bytecode; other contracts and callers are accounts[].',
  'Callers supply bytecode or transaction fields; this server does not ship demo programs.',
  'When you report results to the user, use plain language — paid gas, call gas (bytecode frame),',
  'regular-gas breakdown, state gas, block header total, prefunded storage — not JSON field names',
  '(gasUsed, txRegularGas, accounts[], gasUsedScope) unless they ask for raw fields or a paste of the tool JSON.',
  'Run results include provenance.forkLabel and forkMascotEmoji when set — prefer those (with mascot) when naming the fork in replies.',
].join(' ')
